spring:
  application:
    name: ServiceWeb
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tiknology
    username: root
    password: daviAleixo1811@100
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  flyway:
    baselineVersion: 0
    enabled: true

server:
  error:
    include-stacktrace: never