
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: FCCPD
      MYSQL_PASSWORD: Senha@123456
      MYSQL_ROOT_PASSWORD: daviAleixo1811@100
      MYSQL_DATABASE: tiknology
    volumes:
      - db_data:/var/lib/mysqld
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: FCCPD
      DB_PASSWORD: Senha@123456
      DB_ROOT_PASSWORD: daviAleixo1811@100
      DB_NAME: tiknology
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tiknology
    ports:
      - "8080:8080"  # Mapeia a porta da aplicação
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db_data: